# This workflow is automatically triggered on release/tag and will bump the
# version in the package.json and respective android/ios files
#
name: Release Version

on:
  release:
    types: [created]

env:
  GIT_AUTHOR_EMAIL: '17721880+joaocarmo@users.noreply.github.com'
  GIT_AUTHOR_NAME: 'Jo√£o Carmo'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v14 (LTS)
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - uses: c-hive/gha-yarn-cache@v1
    - name: Install dependencies
      run: |
        yarn --frozen-lockfile

    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Bump the version
      run: |
        npm version ${{ steps.get_release.outputs.tag_name }}

    - name: Config git
      run: |
        git config --global user.email "${{ env.GIT_AUTHOR_EMAIL }}"
        git config --global user.email "${{ env.GIT_AUTHOR_NAME }}"

    - name: Commit the version change
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Release ${{ steps.get_release.outputs.tag_name }}
        commit_options: '--no-verify'
        commit_user_email: ${{ env.GIT_AUTHOR_EMAIL }}
        commit_user_name: ${{ env.GIT_AUTHOR_NAME }}
