# This workflow is automatically triggered on release/tag and will bump the
# version in the package.json and respective android/ios files
#
name: Release Version

on:
  release:
    types: [created]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'
    - name: Use Node.js v14 (LTS)
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - uses: c-hive/gha-yarn-cache@v1
    - name: Install dependencies
      run: |
        yarn --frozen-lockfile

    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.2
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Bump the version
      run: |
        git config --local user.name "${{ secrets.GIT_AUTHOR_NAME }}"
        git config --local user.email "${{ secrets.GIT_AUTHOR_EMAIL }}"
        npm version --no-commit-hooks --no-git-tag-version ${{ steps.get_release.outputs.tag_name }}

    - name: Commit and push the version change
      run: |
        git add .
        git commit -m "Release ${{ steps.get_release.outputs.tag_name }}" --no-gpg-sign --no-verify --signoff
        git push

    - name: Trigger the App Store build and release
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Publish App Store
        token: ${{ github.token }}

    - name: Trigger the Play Store build and release
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Publish Play Store
        token: ${{ github.token }}
        inputs: '{ "track": "internal" }'
